# Generated by Django 4.2.2 on 2023-07-24 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0007_entradablog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entregable',
        ),
    ]
