# Generated by Django 4.2.2 on 2023-07-24 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0009_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradablog',
            name='autor',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='EntradaBlog',
        ),
    ]
